apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-web-app
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: uber-web-app
  template:
    metadata:
      labels:
        app: uber-web-app
    spec:
      containers:
      - name: uber-web-app
        image: gouthamc125/uber-web-app:v1
        ports:
        - containerPort: 3000  # Port your application listens on

