apiVersion: v1
kind: Service
metadata:
  name: uber-web-app
  lables:
    app: uber-web-app
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 3000  # Port your application listens on inside the pods
  selector:
    app: uber-web-app
  type: ClusterIP

