apiVersion: v1
kind: Service
metadata:
  name: uber-web-app
spec:
  selector:
    app: uber-web-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 3000  # Port your application listens on inside the pods
  type: LoadBalancer

