apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-web-app
  labels:
    app: uber-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uber-web-app
  template:
    metadata:
      labels:
        app: uber-web-app
    spec:
      containers:
      - name: uber-web-app
        image: gouthamc125/uber-web-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
